# Generated by Django 4.2.7 on 2023-11-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_recipes_ingredients_delete_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='url_img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
