# Generated by Django 4.2.6 on 2023-10-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_clientcontacts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='seller',
            field=models.ForeignKey(null='N/A', on_delete=django.db.models.deletion.PROTECT, to='app.usercollaborator'),
            preserve_default='N/A',
        ),
    ]
