# Generated by Django 4.2.7 on 2023-11-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipes_description_recipes_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinventory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoryproduct'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productsinventory'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usercollaborator'),
        ),
    ]
