# Generated by Django 4.2.6 on 2023-10-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sales_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='productName',
        ),
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(null='N/A', on_delete=django.db.models.deletion.PROTECT, to='app.productsinventory'),
            preserve_default='N/A',
        ),
    ]
