# Generated by Django 4.2.6 on 2023-10-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_suppliers_rename_nombre_ingredients_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(null='N/A'),
            preserve_default='N/A',
        ),
    ]
