# Generated by Django 4.2.6 on 2023-10-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_recipes_ingredients_recipes_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='producst',
            new_name='products',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
